In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
#Esercitazione 1
import torch

In [3]:
tensorA = torch.rand(7,7)
tensorB = torch.rand(1,7)

Matmul = tensorA @ tensorB.T
print(Matmul)

tensor([[1.4353],
        [1.4234],
        [1.0614],
        [1.2688],
        [0.9870],
        [0.8112],
        [1.4216]])


In [5]:
#set random seed 
torch.manual_seed(0)

tensorA = torch.rand(7,7)
tensorB = torch.rand(1,7)

Matmul = tensorA @ tensorB.T
print(Matmul)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [13]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234) 

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create a random tensor (2, 3) directly on the GPU
tensorA = torch.randn(2, 3, device=device)
tensorB = torch.randn(2, 3, device=device)


matmul = tensorA @ tensorB.T
print(matmul)

tensor([[-0.6738, -0.6621],
        [ 2.4030,  0.2114]])


In [14]:
max = matmul.max()
min = matmul.min()
argmin = matmul.argmin()
argmax = matmul.argmax()

print(max , min, argmin, argmax)

tensor(2.4030) tensor(-0.6738) tensor(0) tensor(2)


In [16]:
torch.manual_seed(7)

tensor = torch.rand(1,1,1,10)

print(tensor)

tensor = tensor.squeeze() # rimuove tutte le dimensioni  = 1

print(tensor)
print(tensor.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
